/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_ewhale_myapplication_JNITest */

#ifndef _Included_cn_ewhale_myapplication_JNITest
#define _Included_cn_ewhale_myapplication_JNITest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_ewhale_myapplication_JNITest
 * Method:    get
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cn_ewhale_myapplication_JNITest_get
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
